rosetta:
    # OPAC configuration variables.
    # This section is used to customize the appearance of the Web UI.
    opac:
        app_name: 'Rosetta Demo'
        covers_expiration: '+90 days'

    # Wikidata configuration values.
    wikidata:
        language: 'es'

    # Primary search sources to be used to get available materials from a given library.
    # Multiple sources are allowed.
    databases:
        - id: 'uva'
          name: 'Universidad de Valladolid'
          short_name: 'UVa'
          external_link: 'https://almena.uva.es/search/i?search={{isbn13}}'
          provider:
              type: App\RosettaBundle\Provider\Z3950
              preset: 'millennium'
              url: 'almena.uva.es:210/INNOPAC'
              covers_url: 'https://www.syndetics.com/index.php?isbn={{isbn13}}/LC.GIF&client=uvalla'

        - id: 'ur'
          name: 'Universidad de La Rioja'
          short_name: 'UR'
          external_link: 'http://catalogo.rebiun.org/rebiun/doc?q={{isbn10}}'
          provider:
              type: App\RosettaBundle\Provider\Z3950
              url: 'merly.unirioja.es:9000/ABSYSE'
              covers_url: 'https://www.syndetics.com/index.php?isbn={{isbn13}}/LC.GIF&client=uvalla'

        - id: 'ub'
          name: 'Universitat de Barcelona'
          short_name: 'UB'
          external_link: 'https://cataleg.ub.edu/search*spi/?searchtype=i&searcharg={{isbn13}}'
          provider:
              type: App\RosettaBundle\Provider\Z3950
              preset: 'millennium'
              url: 'ub.cbuc.cat:210/INNOPAC'
              covers_url: 'https://cobertes.csuc.cat/cobertes.php?isbn={{isbn13}}&institucio=UB'

    # Third-party sources to be used to fix incorrect values and fill-in missing
    # fields from entities fetched from the local databases.
    external_providers:
        - type: App\RosettaBundle\Provider\GoogleBooks
          get_holdings: true
