rosetta:
    # Primary search sources to be used to get available materials from a given library.
    # Multiple sources are allowed.
    sources:
        - id: 'uned'
          name: 'UNED'
          description: 'Universidad Nacional de Educación a Distancia'
          provider:
              type: App\RosettaBundle\Provider\Z3950
              preset: 'unicorn'
              url: 'biblio15.uned.es:2200/unicorn'

        - id: 'ub'
          name: 'UB'
          description: 'Universitat de Barcelona'
          provider:
              type: App\RosettaBundle\Provider\Z3950
              preset: 'millenium'
              url: 'ub.cbuc.cat:210/INNOPAC'
