rosetta:
    # OPAC configuration variables.
    # This section is used to customize the appearance of the Web UI.
    opac:
        app_name: 'Rosetta Demo'

    # Primary search sources to be used to get available materials from a given library.
    # Multiple sources are allowed.
    databases:
        - id: 'uva'
          name: 'Universidad de Valladolid'
          short_name: 'UVa'
          provider:
              type: App\RosettaBundle\Provider\Innopac
              url: 'http://almena.uva.es/search/a?searchtype=Y&searcharg={{query}}&SORT=D'

        - id: 'ur'
          name: 'Universidad de La Rioja'
          short_name: 'UR'
          provider:
              type: App\RosettaBundle\Provider\Z3950
              url: 'merly.unirioja.es:9000/ABSYSE'

        - id: 'ub'
          name: 'Universitat de Barcelona'
          short_name: 'UB'
          provider:
              type: App\RosettaBundle\Provider\Z3950
              preset: 'millenium'
              url: 'ub.cbuc.cat:210/INNOPAC'

    # Third-party sources to be used to fix incorrect values and fill-in missing
    # fields from entities fetched from the local databases.
    external_providers:
        - type: App\RosettaBundle\Provider\GoogleBooks
