dist: xenial
language: php

notifications:
    email: false

matrix:
    fast_finish: true
    include:
        - php: 7.1.3
        - php: 7.2
        - php: 7.3
        - php: nightly # Just in case, let's ensure app will run on future PHP versions
    allow_failures:
        - php: 7.1.3
        - php: nightly

cache:
    directories:
        - vendor
        - node_modules
        - bin/.phpunit

addons:
    mariadb: '10.3' # Install MariaDB Server

services:
    - mariadb # Start MariaDB service

before_install:
    - sudo apt install -y yaz libyaz-dev # Install YAZ apt package
    - pecl channel-update pecl.php.net   # Update PECL
    - printf "\n" | pecl install yaz     # Download and build YAZ PHP extension
    - nvm install stable                 # Install NodeJS
    - composer self-update               # Make sure Composer itself is updated before continuing

install:
    - echo "$DEPLOY_SSH_KEY" >> ~/.ssh/known_hosts # Trust deploy server public key
    - composer install --no-interaction            # Install Composer dependencies
    - yarn install                                 # Install NodeJS dependencies
    - yarn build                                   # Build static assets

script:
    - composer validate --no-check-all --strict # Validate composer.json and composer.lock
    - php ./bin/console lint:yaml config        # Validate YAML config files syntax
    - php ./bin/console lint:twig templates     # Validate Twig templates syntax
    - php ./bin/console security:check          # Try to find vulnerabilities in dependencies
    - php ./bin/console lint:xliff translations # Validate XLIFF translations
    - php ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction # Validate Doctrine mappings
    - php ./bin/phpunit                         # Run tests

deploy:
    provider: script
    script: bash .docker/deploy.sh
    on:
        php: 7.2 # Deploy once per build
        branch: master
