version: '2'

services:
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - app-source:/rosetta
        depends_on:
            - php
            - db
    db:
        image: mariadb
        ports:
            - 3306:3306
        restart: always
        volumes:
            - app-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rosetta_pass
            MYSQL_USER: rosetta_user
            MYSQL_PASSWORD: rosetta_pass
            MYSQL_DATABASE: rosetta_db
    php:
        build:
            context: .
            args:
                app_env: prod
                db_url: mysql://rosetta_user:rosetta_pass@db:3306/rosetta_db
        ports:
            - 9000:9000
        restart: always
        volumes:
            - app-source:/rosetta
        depends_on:
          - db

volumes:
    app-source:
    app-data:
