version: '2'

services:
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - app-volume:/rosetta
        depends_on:
            - php
    php:
        build: .
        ports:
            - 9000:9000
        restart: always
        volumes:
            - app-volume:/rosetta

volumes:
    app-volume:
